name: Task-Sync App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your preferred Python 3 version.

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython  # Install Cython before installing Kivy
        pip install -r requirements.txt

    - name: Run Application Tests
      run: |
        python -m unittest discover -s tests  # Adjust this line based on your test setup
